# Generated by Django 4.0.7 on 2022-10-24 09:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('thing_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datasource_type', models.CharField(choices=[('SFTP', 'SFTP'), ('MQTT', 'MQTT')], default='SFTP', max_length=4, verbose_name='Ingest Type')),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('is_ready', models.BooleanField(default=False, verbose_name='Ready')),
                ('sftp_uri', models.URLField(blank=True, null=True)),
                ('sftp_username', models.CharField(blank=True, max_length=1000, null=True)),
                ('sftp_password', models.CharField(blank=True, max_length=1000, null=True)),
                ('sftp_filename_pattern', models.CharField(blank=True, max_length=200, null=True)),
                ('mqtt_uri', models.CharField(blank=True, max_length=1000, null=True)),
                ('mqtt_username', models.CharField(blank=True, max_length=1000, null=True)),
                ('mqtt_password', models.CharField(blank=True, max_length=1000, null=True)),
                ('mqtt_hashed_password', models.CharField(blank=True, max_length=256, null=True)),
                ('mqtt_topic', models.CharField(blank=True, max_length=1000, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Project')),
                ('mqtt_device_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsm.mqttdevicetype')),
            ],
            options={
                'verbose_name': 'Thing',
                'verbose_name_plural': 'Things',
            },
        ),
        migrations.CreateModel(
            name='RawDataStorage',
            fields=[
                ('bucket', models.CharField(max_length=63)),
                ('access_key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tsm.thing')),
            ],
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CsvParser', 'CSV')], default='CsvParser', max_length=100)),
                ('delimiter', models.CharField(blank=True, max_length=1, null=True)),
                ('exclude_headlines', models.IntegerField(blank=True, default=0, null=True)),
                ('exclude_footlines', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp_column', models.IntegerField(blank=True, null=True)),
                ('timestamp_format', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsm.thing')),
            ],
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Project')),
            ],
        ),
    ]
