# Generated by Django 4.0.7 on 2022-09-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='isActivated',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
