# Generated by Django 4.1.2 on 2022-10-24 15:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='delimiter',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Column delimiter'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='exclude_footlines',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of footlines to exclude'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='exclude_headlines',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of headlines to exclude'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='timestamp_column',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='type',
            field=models.CharField(choices=[('CsvParser', 'CSV')], default='CsvParser', max_length=100, verbose_name='File type'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='mqtt_device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsm.mqttdevicetype', verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='mqtt_password',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='mqtt_topic',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='mqtt_uri',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Broker URI'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='sftp_filename_pattern',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Filename pattern'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='sftp_password',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='sftp_uri',
            field=models.URLField(blank=True, null=True, verbose_name='Fileserver URI'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='sftp_username',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='thing_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='ID'),
        ),
    ]
