# Generated by Django 4.0.7 on 2022-09-09 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0002_thing_isactivated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='isActivated',
            new_name='isActive',
        ),
        migrations.AddField(
            model_name='thing',
            name='isReady',
            field=models.BooleanField(default=False, verbose_name='Ready'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='datasource_type',
            field=models.CharField(choices=[('SFTP', 'SFTP'), ('MQTT', 'MQTT')], default='SFTP', max_length=4, verbose_name='Ingest Type'),
        ),
    ]
