# Generated by Django 4.0.7 on 2022-09-09 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0004_rename_isactive_thing_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parser',
            old_name='parser_type',
            new_name='type',
        ),
    ]
