# Generated by Django 4.0.7 on 2022-09-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0005_rename_parser_type_parser_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='type',
            field=models.CharField(choices=[('CsvParser', 'CSV')], default='CsvParser', max_length=100),
        ),
    ]
