# Generated by Django 4.0.7 on 2022-09-09 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0006_alter_parser_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parser',
            old_name='time_column',
            new_name='timestamp_column',
        ),
        migrations.RenameField(
            model_name='parser',
            old_name='timestamp_expression',
            new_name='timestamp_format',
        ),
    ]
