# Generated by Django 4.0.7 on 2022-09-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0007_rename_time_column_parser_timestamp_column_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='exclude_footlines',
            field=models.IntegerField(default=0),
        ),
    ]
