# Generated by Django 4.0.7 on 2022-09-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0008_parser_exclude_footlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttconfig',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='topic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='delimiter',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='exclude_footlines',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='exclude_headlines',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='timestamp_column',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parser',
            name='timestamp_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sftpconfig',
            name='filename_pattern',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sftpconfig',
            name='password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sftpconfig',
            name='uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sftpconfig',
            name='username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
