# Generated by Django 4.0.7 on 2022-09-13 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0010_alter_thing_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tsm.mqttdevicetype'),
        ),
        migrations.AddConstraint(
            model_name='parser',
            constraint=models.UniqueConstraint(fields=('sftp_config', 'position'), name='unique position per sftp_config'),
        ),
    ]
