# Generated by Django 4.0.7 on 2022-09-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0011_parser_position_alter_mqttconfig_device_type_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='parser',
            name='unique position per sftp_config',
        ),
        migrations.RemoveField(
            model_name='parser',
            name='position',
        ),
    ]
