# Generated by Django 4.0.7 on 2022-09-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0012_remove_parser_unique position per sftp_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
