# Generated by Django 4.0.7 on 2022-09-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0013_database_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttconfig',
            name='hashed_password',
            field=models.CharField(blank=True, max_length=112, null=True),
        ),
    ]
