# Generated by Django 4.0.7 on 2022-09-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0015_alter_mqttconfig_hashed_password'),
        ('tsm', '0015_alter_rawdatastorage_bucket'),
    ]

    operations = [
    ]
