# Generated by Django 4.0.7 on 2022-09-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0015_alter_rawdatastorage_bucket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='is_active',
            new_name='is_created',
        ),
    ]
