# Generated by Django 4.0.7 on 2022-09-23 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0016_merge_20220915_1628'),
        ('tsm', '0016_rename_is_active_thing_is_created'),
    ]

    operations = [
    ]
