# Generated by Django 4.0.7 on 2022-09-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0017_merge_20220923_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='is_created',
            field=models.BooleanField(default=False, verbose_name='Created'),
        ),
    ]
