# Generated by Django 4.0.8 on 2022-10-12 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0018_alter_thing_is_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='parser',
            name='timestamp_format',
        ),
        migrations.AddField(
            model_name='parser',
            name='is_active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
