# Generated by Django 4.0.7 on 2022-10-13 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tsm', '0018_alter_thing_is_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mqttconfig',
            options={'verbose_name': 'MQTT Configuration', 'verbose_name_plural': 'MQTT Configuration'},
        ),
        migrations.AlterModelOptions(
            name='sftpconfig',
            options={'verbose_name': 'SFTP Configuration', 'verbose_name_plural': 'SFTP Configuration'},
        ),
        migrations.RemoveField(
            model_name='database',
            name='thing',
        ),
        migrations.AddField(
            model_name='database',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.group', verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
