# Generated by Django 4.0.8 on 2022-10-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0019_remove_parser_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='end_time',
        ),
        migrations.AddField(
            model_name='parser',
            name='timestamp_format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
