# Generated by Django 4.0.7 on 2022-10-13 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0019_alter_mqttconfig_options_alter_sftpconfig_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='group_id',
            new_name='group',
        ),
    ]
