# Generated by Django 4.0.8 on 2022-10-12 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0020_remove_parser_end_time_parser_timestamp_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
