# Generated by Django 4.0.7 on 2022-10-13 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0020_rename_group_id_thing_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='database',
            old_name='group_id',
            new_name='group',
        ),
    ]
