# Generated by Django 4.0.8 on 2022-10-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0021_alter_parser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sftpconfig',
            name='uri',
            field=models.URLField(blank=True, null=True),
        ),
    ]
