# Generated by Django 4.0.7 on 2022-10-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0021_rename_group_id_database_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='is_created',
        ),
    ]
