# Generated by Django 4.0.7 on 2022-10-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0022_remove_database_is_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
