# Generated by Django 4.0.8 on 2022-10-13 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0022_alter_sftpconfig_uri'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parser',
            unique_together={('is_active', 'sftp_config')},
        ),
    ]
