# Generated by Django 4.0.8 on 2022-10-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsm', '0023_alter_parser_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='parser',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='parser',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active', 'sftp_config'), name='unique_parser'),
        ),
    ]
