version: "3.7"

services:
  db:
    image: "postgres:14-alpine"
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      - "POSTGRES_NAME=${POSTGRES_NAME:-postgres}"
      - "POSTGRES_USER=${POSTGRES_USER:-postgres}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}"
  web:
    build: "."
#    command: "gunicorn main.wsgi:application --bind 0.0.0.0:8000"
#    entrypoint: ""
    command: "runserver 0.0.0.0:8000"
    volumes:
      - ".:/home/appuser/app/"
    ports:
      - "127.0.0.1:8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - "POSTGRES_NAME=${POSTGRES_NAME:-postgres}"
      - "POSTGRES_USER=${POSTGRES_USER:-postgres}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}"
      - "POSTGRES_HOST=${POSTGRES_HOST:-db}"
      - "PUBLISH_THING_TO_BROKER=${PUBLISH_THING_TO_BROKER:-True}"
      - "TSM_DATABASE_HOST=${TSM_DATABASE_HOST}"
      - "TSM_DATABASE_NAME=${TSM_DATABASE_NAME}"
      - "MQTT_BROKER_HOST=${MQTT_BROKER_HOST}"
      - "MQTT_USER=${MQTT_USER}"
      - "MQTT_PASSWORD=${MQTT_PASSWORD}"
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}"
    depends_on:
      - "db"

volumes:
  postgres_data: