# Generated by Django 4.0.7 on 2022-09-01 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('SFTP', 'SFTP'), ('MQTT', 'MQTT')], default='SFTP', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='ParserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MqttSettings',
            fields=[
                ('datasource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.datasource')),
                ('protocol', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SftpSettings',
            fields=[
                ('datasource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.datasource')),
                ('path', models.CharField(max_length=200)),
                ('filename_pattern', models.CharField(max_length=200)),
                ('poll_interval', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('serial_number', models.CharField(max_length=1000)),
                ('project', models.CharField(max_length=1000)),
                ('datasource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('delimiter', models.CharField(max_length=200)),
                ('exclude_headlines', models.IntegerField(default=0)),
                ('exclude_footer', models.IntegerField(default=0)),
                ('timestamp_field', models.IntegerField()),
                ('timestamp_expression', models.CharField(max_length=200)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.thing')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parsertype')),
            ],
        ),
    ]
