# Generated by Django 4.0.3 on 2022-03-24 16:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatastoreType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ParserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RawdataStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Shuttle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('host', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('type', models.CharField(choices=[('SFTP', 'SFTP'), ('MQTT', 'MQTT')], default='SFTP', max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='MqttSettings',
            fields=[
                ('shuttle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.shuttle')),
                ('protocol', models.CharField(max_length=200)),
                ('client_name', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SftpSettings',
            fields=[
                ('shuttle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.shuttle')),
                ('path', models.CharField(max_length=200)),
                ('filename_pattern', models.CharField(max_length=200)),
                ('poll_interval', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('delimiter', models.CharField(max_length=200)),
                ('exclude_headlines', models.IntegerField(default=0)),
                ('exclude_footer', models.IntegerField(default=0)),
                ('timestamp_field', models.IntegerField()),
                ('timestamp_expression', models.CharField(max_length=200)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parsertype')),
            ],
        ),
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.datastoretype')),
            ],
        ),
        migrations.CreateModel(
            name='Datasource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('serial_number', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=4000)),
                ('project', models.CharField(max_length=1000)),
                ('contacts', models.CharField(max_length=1000)),
                ('datasource_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('datastore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.datastore')),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parser')),
                ('rawdata_storage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.rawdatastorage')),
                ('shuttle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.shuttle')),
            ],
        ),
    ]
