# Generated by Django 4.0.7 on 2022-09-01 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('schema', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('thing_id', models.CharField(max_length=1000)),
                ('project', models.CharField(max_length=1000)),
                ('datasource_type', models.CharField(choices=[('SFTP', 'SFTP'), ('MQTT', 'MQTT')], default='SFTP', max_length=4)),
                ('sftp_uri', models.CharField(blank=True, max_length=1000, null=True)),
                ('sftp_username', models.CharField(blank=True, max_length=1000, null=True)),
                ('sftp_password', models.CharField(blank=True, max_length=1000, null=True)),
                ('sftp_filename_pattern', models.CharField(blank=True, max_length=200, null=True)),
                ('mqtt_uri', models.CharField(blank=True, max_length=1000, null=True)),
                ('mqtt_username', models.CharField(blank=True, max_length=1000, null=True)),
                ('mqtt_password', models.CharField(blank=True, max_length=1000, null=True)),
                ('mqtt_topic', models.CharField(blank=True, max_length=1000, null=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.database')),
            ],
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('parser_type', models.CharField(choices=[('CSV', 'CSV')], default='CSV', max_length=10)),
                ('delimiter', models.CharField(max_length=200)),
                ('exclude_headlines', models.IntegerField(default=0)),
                ('time_column', models.IntegerField()),
                ('timestamp_expression', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.thing')),
            ],
        ),
    ]
