# Generated by Django 4.0.7 on 2022-09-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='id',
        ),
        migrations.AlterField(
            model_name='database',
            name='thing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.thing'),
        ),
    ]
