# Generated by Django 4.0.3 on 2022-03-24 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='datastore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.datastore'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='rawdata_storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rawdatastorage'),
        ),
        migrations.AlterField(
            model_name='datasource',
            name='shuttle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shuttle'),
        ),
    ]
