# Generated by Django 4.0.7 on 2022-09-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='parser',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
