# Generated by Django 4.0.7 on 2022-09-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_mqttdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttconfig',
            name='type',
            field=models.CharField(choices=[('campbell_cr6', 'campbell_cr6')], default='campbell_cr6', max_length=100),
        ),
        migrations.DeleteModel(
            name='MqttDevice',
        ),
    ]
