# Generated by Django 4.0.7 on 2022-09-02 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_thing_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttConfig',
            fields=[
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.thing')),
                ('sftp_uri', models.CharField(max_length=1000)),
                ('sftp_username', models.CharField(max_length=1000)),
                ('sftp_password', models.CharField(max_length=1000)),
                ('sftp_filename_pattern', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SftpConfig',
            fields=[
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.thing')),
                ('uri', models.CharField(max_length=1000)),
                ('username', models.CharField(max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('topic', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='thing',
            name='mqtt_password',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='mqtt_topic',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='mqtt_uri',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='mqtt_username',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='sftp_filename_pattern',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='sftp_password',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='sftp_uri',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='sftp_username',
        ),
    ]
