# Generated by Django 4.0.7 on 2022-09-05 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_mqttconfig_type_delete_mqttdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mqttconfig',
            name='mqtt_password',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='mqtt_topic',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='mqtt_uri',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='mqtt_username',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='parser',
            name='delimiter',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='parser',
            name='exclude_headlines',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='parser',
            name='parser_type',
            field=models.CharField(choices=[('CSV', 'CSV')], default='CSV', max_length=100),
        ),
        migrations.AlterField(
            model_name='parser',
            name='time_column',
            field=models.IntegerField(),
        ),
    ]
