# Generated by Django 4.0.7 on 2022-09-05 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mqttconfig_mqtt_password_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqttconfig',
            old_name='type',
            new_name='device_type',
        ),
        migrations.RenameField(
            model_name='mqttconfig',
            old_name='mqtt_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='mqttconfig',
            old_name='mqtt_topic',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='mqttconfig',
            old_name='mqtt_uri',
            new_name='uri',
        ),
        migrations.RenameField(
            model_name='mqttconfig',
            old_name='mqtt_username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='sftpconfig',
            old_name='sftp_filename_pattern',
            new_name='filename_pattern',
        ),
        migrations.RenameField(
            model_name='sftpconfig',
            old_name='sftp_password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='sftpconfig',
            old_name='sftp_uri',
            new_name='uri',
        ),
        migrations.RenameField(
            model_name='sftpconfig',
            old_name='sftp_username',
            new_name='username',
        ),
    ]
