# Generated by Django 4.0.7 on 2022-09-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_thing_thing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sftpconfig',
            name='thing',
        ),
        migrations.AddField(
            model_name='thing',
            name='mqtt_password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='mqtt_topic',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='mqtt_uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='mqtt_username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='sftp_filename_pattern',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='sftp_password',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='sftp_uri',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='thing',
            name='sftp_username',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='thing_id',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='MqttConfig',
        ),
        migrations.DeleteModel(
            name='SftpConfig',
        ),
    ]
