# Generated by Django 4.0.7 on 2022-09-05 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_type_mqttconfig_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sftpconfig',
            name='filename_pattern',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='sftpconfig',
            name='password',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sftpconfig',
            name='uri',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sftpconfig',
            name='username',
            field=models.CharField(max_length=1000),
        ),
    ]
