# Generated by Django 4.0.7 on 2022-09-08 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_sftpconfig_filename_pattern_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={'verbose_name': 'Thing', 'verbose_name_plural': 'Things'},
        ),
        migrations.RemoveField(
            model_name='thing',
            name='userid',
        ),
        migrations.AddField(
            model_name='thing',
            name='group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
