# Generated by Django 4.0.7 on 2022-09-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_thing_thing_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parser',
            name='name',
        ),
    ]
