# Generated by Django 4.0.7 on 2022-09-08 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_thing_project_alter_thing_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MqttDeviceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='mqttconfig',
            name='device_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mqttdevicetype'),
        ),
    ]
