# Generated by Django 4.0.7 on 2022-09-08 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mqttdevicetype_alter_mqttconfig_device_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawDataStorage',
            fields=[
                ('bucket', models.CharField(max_length=1000)),
                ('access_key', models.CharField(max_length=200)),
                ('secret_key', models.CharField(max_length=200)),
                ('thing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.thing')),
            ],
        ),
    ]
